<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-07 21:45

=======
# Generated by Django 5.2.7 on 2025-11-07 16:29

import django.contrib.auth.models
import django.core.validators
import django.utils.timezone
import test_app.models
>>>>>>> 0e003c4962787e63c801a33bb7f977651a386d48
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('auth', '0012_alter_user_first_name_max_length'),
>>>>>>> 0e003c4962787e63c801a33bb7f977651a386d48
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=70, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('age', models.PositiveSmallIntegerField()),
                ('followers_count', models.PositiveBigIntegerField()),
                ('posts_count', models.PositiveIntegerField()),
                ('comments_count', models.PositiveIntegerField()),
                ('engagement_rate', models.FloatField()),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('email', models.EmailField(max_length=75, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('role', models.CharField(choices=[('lib_member', 'Lib Member'), ('admin', 'Admin'), ('moderator', 'Moderator'), ('guest', 'Guest')], default=test_app.models.Role['lib_member'], max_length=35)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')])),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=45, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(120)])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
>>>>>>> 0e003c4962787e63c801a33bb7f977651a386d48
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField()),
<<<<<<< HEAD
            ],
=======
                ('pages', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ['published_date'],
                'get_latest_by': 'published_date',
                'default_related_name': 'books',
                'indexes': [models.Index(fields=['title', 'published_date'], name='idx_book_title_pub_date')],
                'constraints': [models.UniqueConstraint(fields=('title', 'published_date'), name='unq_title_pub_date'), models.CheckConstraint(condition=models.Q(('pages__gte', 0)), name='book_pages_constraint')],
            },
>>>>>>> 0e003c4962787e63c801a33bb7f977651a386d48
        ),
    ]
