# Generated by Django 5.2.7 on 2025-11-09 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='book',
            name='unq_title_pub_date',
        ),
        migrations.RemoveConstraint(
            model_name='book',
            name='book_pages_constraint',
        ),
    ]
